### ISSUE TITLE
Can I use no JDBC?

### ISSUE THREAD

**Issue by kichigai** [bombinating/jooq-gradle-plugin#1]
I find this goooood plugin for Kotlin dsl.

But, I want to generate from JPA Entity.
Can I User no jdbc?

Related jooq doc is `https://www.jooq.org/doc/latest/manual/code-generation/codegen-jpa/`

**Comment by bombinating** [comment]
You are correct. I'll make the change.

**Comment by bombinating** [comment]
Note that the versioning scheme has changed for this plugin. This change is in version 1.0.0 of the plugin. I will delete the 3.12.1 version of the plugin.
