### ISSUE TITLE
Error adding jooqRuntime

### ISSUE THREAD

**Issue by joshuaswilcox** [bombinating/jooq-gradle-plugin#22]
I have added the

    jooqRuntime(group = "org.postgresql", name = "postgresql", version = "42.2.6")

as the README states, but it fails with this error

    > Cannot set the value of read-only property 'name' for project ':server' of type org.gradle.api.Project.

Any ideas as to a fix for this?

**Comment by bombinating** [comment]
That's a strange error! What version of the plugin are you using and what version of Gradle?

Are you putting the `jooqRuntime` piece inside of the `dependencies` block in your build.gradle.kts file?

You can see an example of how it is used here: https://github.com/bombinating/jooq-gradle-plugin-example/blob/master/simple/build.gradle.kts#L56

**Comment by joshuaswilcox** [comment]
I am

    plugins {
        id "org.jetbrains.kotlin.jvm" version "1.3.70"
        id "dev.bombinating.jooq-codegen" version "1.7.0"
    }
    project(':server') {
        apply plugin: 'kotlin'
        apply plugin: 'dev.bombinating.jooq-codegen'
        dependencies {
            ...
            jooqRuntime(group = "org.postgresql", name = "postgresql", version = "9.3-1102.jdbc41")
        }
    }

**Comment by bombinating** [comment]
The error you're getting isn't about the plugin, I don't think. It seems to be saying that you're setting the Project.name but name is a val not a var (there's only a getter).

Do you have any code in your build.gradle.kts file that is setting name or project.name?

If you comment out the `jooqRuntime` line, does the error go away or is it still there?

**Comment by joshuaswilcox** [comment]
So I changed it to `jooqRuntime('postgresql:postgresql:9.3-1102.jdbc41')` and that seems to have passed that, but now i get `Could not find method jdbc() for arguments` for 

    jooq {
        version = jooqVersion
        jdbc {
            driver = "org.postgresql.Driver"
            url = "jdbc:postgresql://localhost:5432/mydatabase"
            user = "user"
            password = ""
        }
        generator {
            name = "org.jooq.codegen.JavaGenerator"
            database {
                name = "org.jooq.meta.postgres.PostgresDatabase"
                includes = ".*"
                excludes = ""
                inputSchema = "public"
            }
            target {
                packageName = "com.my.app"
                directory = "./generated"
            }
            strategy {
                name = "org.jooq.codegen.DefaultGeneratorStrategy"
            }
        }
        logging = Logging.WARN
    }

and if it matters its a build.gradle, not build.gradle.kt

**Comment by joshuaswilcox** [comment]
More specifically the error is 

    Could not find method jdbc() for arguments [build_3vtfdc0f2zeza3lsyhisy8l31$_run_closure3$_closure7$_closure12@6d7056cc] on version: 3.12.1, edition: OpenSource, config: dev.bombinating.gradle.jooq.JooqConfigImpl@620e6da8 of type dev.bombinating.gradle.jooq.JooqExtension.

**Comment by bombinating** [comment]
It looks like you're using Groovy not Kotlin for your build script (i.e., your build script is named build.gradle not build.gradle.kts). 

All of the documentation and examples are using Kotlin for the build script. If you're using Groovy, you can take a look at one example that does use Groovy: https://github.com/bombinating/jooq-gradle-plugin-example/blob/master/groovy/build.gradle

Alternatively, here is a Gradle plugin that utilizes Groovy for generating jOOQ classes: https://github.com/etiennestuder/gradle-jooq-plugin

**Comment by joshuaswilcox** [comment]
Yeah you are correct, its a weird thing with our setup, but the rest of the app is Kotlin. So i got it to work with 

    jooq {
        use(ConfigExtKt) {
            version = '3.12.1'
            jdbc {
                it.driver = "org.postgresql.Driver"
                it.url = "jdbc:postgresql://localhost:5432/my_db"
                it.user = "user"
                it.password = ""
            }
            generator {
                it.database {
                    it.name = "org.jooq.meta.postgres.PostgresDatabase"
                    it.includes = ".*"
                    it.excludes = "SchemaMigrations"
                    it.inputSchema = "public"
                }
                it.target {
                    it.packageName = "com.my.domain"
                    it.directory = "./generated"
                }
                it.generate {
                    it.generatedAnnotation = true
                }
            }
        }
    }

but i guess i was confused and thought this was to generate Kotlin classes for all the tables, rather than just the build script support for Kotlin.  Thanks for your help!
